services:
  - type: web
    name: sinhala-movie-bot
    env: python
    runtime: python-3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: CHANNEL_ID
        value: "@sinhalamoviez"
      - key: HELP_MESSAGE_ID
        value: "12942"
